### ISSUE TITLE
Enhancements 

### ISSUE THREAD

**Issue by sain0136** [sain0136/myrotary-projects#101]
#### Summary
The issue is related to enhancing the user experience when navigating to the "My Profile" section. Currently, the "My Profile" section is at the bottom of the settings tab. The goal is to make it a separate view accessible by clicking on the profile picture then myprofile 

#### Tasks to Complete
- [x] Extract the "My Profile" section from the settings tab.
- [x] Create a new Vue component for "My Profile" under `modules/admin/views`.
- [x] Implement Vue Router path to navigate to the new "My Profile" component.
- [x] Ensure that clicking the profile picture and my profile navigates to the new "My Profile" view.

Bonus extra 5 dollars 
- [x] make the profile picture appear above upload and when they upload new picture it changes 

#### Technical Details
- **Languages**: HTML, CSS, JavaScript, Vue.js
- **Libraries**: Vue Router

#### Summary
The issue is related to adding a feature in the "Districts" tab under "Admins" that allows filtering of admins based on the selected district.

#### Tasks to Complete
- [x] Add a dropdown to select a district.
- [x] Implement logic to filter the admins table based on the selected district.
- [x] Ensure the table updates dynamically when a different district is selected.
